### ISSUE TITLE
I can not disable the login with facebook and twitter in the iframe

### ISSUE THREAD

**Issue by will94290** [pol-is/polis-issues#81] opened 2017-11-13 16:18 UTC
Hi,
I have a little problem and I need your help 😃 
When I try to disable the login with facebook or twitter that doesn't work.
I disabled the options in my code (in the iframe) with the following data attributes : 
```
data-auth_opt_fb="false"
data-auth_opt_tw="false"
data-auth_opt_allow_3rdparty="false"
```
And that's works if I check my newly created conversation in the admin panel : 
<img width="314" alt="sans_1" src="https://user-images.githubusercontent.com/30505061/32735548-52db6174-c895-11e7-8504-b0914d3a4b2f.PNG">
 
The problem is that even though login with facebook and twitter is disabled once embeded on my page the iframe doesn't behave this way. No matter how my irame is configured it always asked me to login with twitter or facebook :
<img width="526" alt="sans_2" src="https://user-images.githubusercontent.com/30505061/32735590-7077fcec-c895-11e7-8c43-9ac663d604da.PNG">

Do you have that same problem on your side ?

Thanks a lot for your help !

**Comment by mbjorkegren** [comment] 2017-11-14 19:13
This is by design. (sorry the documentation is sparse here)
Some of the parameters are only respected the first time the conversation is loaded. After that point, you need to use the admin panel to change those settings.
If you want to change settings in bulk across many conversations please let us know.

**Comment by patcon** [comment] 2017-11-15 20:54
Is this good to close then?

I made a reference to your understandable confusion on a related issue fyi :)

**Comment by patcon** [comment] 2020-05-05 01:21
I'm going to close this, as it seems there's no more action items. But if you can offer anything else we should put on our todo list, def let us know @will94290 :) thanks!

**Closed by patcon** 2020-05-05 01:21 UTC
